<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>statefun-parent</artifactId>
        <groupId>io.github.kzmlabs.flinkstatefun</groupId>
        <version>3.4.0-KZM-3.0-RC1</version>
        <relativePath>..</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <properties>
        <kafka.version>3.9.1</kafka.version>
    </properties>

    <artifactId>statefun-kafka-io</artifactId>
    <name>statefun-kafka-io</name>
    <dependencies>
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-sdk-embedded</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>${kafka.version}</version>
            <exclusions>
                <!-- This collides with snappy-java brought from  
                        org.apache.flink:flink-streaming-java_${scala.binary.version}
                            org.xerial.snappy:snappy-java:1.1.4
                -->
                <exclusion>
                    <groupId>org.xerial.snappy</groupId>
                    <artifactId>snappy-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
        </dependency>
    </dependencies>
</project>
