<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.kzmlabs.flinkstatefun</groupId>
        <artifactId>statefun-flink</artifactId>
        <version>3.4.0-KZM-3.0-RC1</version>
        <relativePath>..</relativePath>
    </parent>

    <artifactId>statefun-flink-extensions</artifactId>
    <name>statefun-flink-extensions</name>

    <dependencies>
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-sdk-embedded</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-shaded-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-annotations</artifactId>
            <version>${flink.version}</version>
        </dependency>
    </dependencies>

</project>
