# SPDX-License-Identifier: Apache-2.0
version: 2

updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - maven
    groups:
      flink-2x:
        patterns:
          - "org.apache.flink:*"
      aws-sdk:
        patterns:
          - "software.amazon.awssdk:*"
      junit:
        patterns:
          - "org.junit.*"
          - "org.mockito:*"
          - "org.assertj:*"
          - "org.hamcrest:*"
          - "org.awaitility:*"
      logging:
        patterns:
          - "ch.qos.logback:*"
          - "org.slf4j:*"
          - "net.logstash.logback:*"
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: "/statefun-docker/src/main/docker"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: "/statefun-k8s-native-e2e/remote-function"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker
