// SPDX-License-Identifier: Apache-2.0
// Copyright 2014 The Apache Software Foundation

syntax = "proto3";

package io.statefun.sdk.types;

option java_package = "org.apache.flink.statefun.sdk.types.generated";
option java_multiple_files = true;
option go_package = ".;protocol";

// BooleanWrapper represents a StateFun primitive type of a boolean value. This is recognized as:
// io.statefun.types/bool
message BooleanWrapper {
  bool value = 1;
}

// IntWrapper represents a StateFun primitive type of an signed 32 bit integer value. This is recognized as:
// io.statefun.types/int
message IntWrapper {
  sfixed32 value = 1;
}

// FloatWrapper represents a StateFun primitive type of a signed float value. This is recognized as:
// io.statefun.types/float
message FloatWrapper {
  float value = 1;
}

// LongWrapper represents a StateFun primitive type of a signed 64 bit long value. This is recognized as:
// io.statefun.types/long
message LongWrapper {
  sfixed64  value = 1;
}

// DoubleWrapper represents a StateFun primitive type of a double value. This is recognized as:
// io.statefun.types/double
message DoubleWrapper {
  double value = 1;
}

// StringWrapper represents a StateFun string. This is recognized as:
// io.statefun.types/string
message StringWrapper {
  string value = 1;
}
