ARG IMAGE_REGISTRY_PREFIX=
ARG BASE_IMAGE=${IMAGE_REGISTRY_PREFIX}node:16
FROM ${BASE_IMAGE}

WORKDIR /usr/src/app

COPY sdk/ /tmp/sdk

RUN cd /tmp/sdk && \
 npm install && \
 npm run build && \
 npm pack && \
 mv apache-flink-statefun-*.tgz /usr/src/app/apache-flink-statefun.tgz && \
 cd /usr/src/app

COPY remote-function/* /usr/src/app/

RUN npm install

EXPOSE 8000

CMD ["node", "/usr/src/app/smoke.js"]
