# SPDX-License-Identifier: Apache-2.0


FROM openjdk:8

RUN mkdir -p /app
WORKDIR /app
COPY statefun-smoke-e2e-java-*-jar-with-dependencies.jar /app/

EXPOSE 443
CMD java -jar /app/statefun-smoke-e2e-*-jar-with-dependencies.jar
