<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<!-- Copyright 2014 The Apache Software Foundation -->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>statefun-e2e-tests</artifactId>
        <groupId>io.github.kzmlabs.flinkstatefun</groupId>
        <version>3.4.0-KZM-3.0-RC1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>statefun-smoke-e2e-embedded</artifactId>

    <properties>
        <central.skip>true</central.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-flink-harness</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
            <exclusions>
                <!-- conflicts with testcontainers -->
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- smoke end-to-end common -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-smoke-e2e-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Reusing some classes from the driver module, e.g. Ids and Types -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-smoke-e2e-driver</artifactId>
            <version>3.4.0-KZM-3.0-RC1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- embedded module should be built into a fat-jar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <!-- Run shade goal on package phase -->
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <transformers>
                                <!--
                                    aggregate all the META-INF/services files, so that
                                    both DriverModule and EmbeddedFnModule are listed
                                -->
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
