<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>statefun-e2e-tests</artifactId>
        <groupId>io.github.kzmlabs.flinkstatefun</groupId>
        <version>3.4.0-KZM-3.0-RC1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>statefun-smoke-e2e-multilang-harness</artifactId>

    <properties>
        <central.skip>true</central.skip>
    </properties>

    <dependencies>
        <!-- StateFun Harness -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-flink-harness</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Adds Driver module into classpath to be picked up by harness -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-smoke-e2e-driver</artifactId>
            <version>3.4.0-KZM-3.0-RC1</version>
        </dependency>

        <!-- Test scope dependencies -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-smoke-e2e-common</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>
</project>
