<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<!-- Copyright 2014 The Apache Software Foundation -->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>statefun-e2e-tests</artifactId>
        <groupId>io.github.kzmlabs.flinkstatefun</groupId>
        <version>3.4.0-KZM-3.0-RC1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>statefun-smoke-e2e-multilang-base</artifactId>
    <packaging>pom</packaging>

    <properties>
        <central.skip>true</central.skip>
    </properties>

    <dependencies>
        <!-- Testcontainer test utilities, e.g. StatefulFunctionsAppContainers -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-e2e-tests-common</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Smoke E2E test utilities, e.g. SmokeRunner -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-smoke-e2e-common</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Copy Smoke E2E driver module jar to target/statefun-smoke-e2e-driver.jar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <artifactItems>
                        <artifactItem>
                            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
                            <artifactId>statefun-smoke-e2e-driver</artifactId>
                            <version>${project.version}</version>
                            <type>jar</type>
                            <overWrite>true</overWrite>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <destFileName>statefun-smoke-e2e-driver.jar</destFileName>
                        </artifactItem>
                    </artifactItems>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
