<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.kzmlabs.flinkstatefun</groupId>
        <artifactId>statefun-flink</artifactId>
        <version>3.4.0-KZM-3.0-RC1</version>
        <relativePath>..</relativePath>
    </parent>

    <artifactId>statefun-flink-io-bundle</artifactId>
    <name>statefun-flink-io-bundle</name>

    <properties>
        <additional-sources.dir>target/additional-sources</additional-sources.dir>
    </properties>

    <dependencies>
        <!-- Stateful Functions sdk -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-sdk-embedded</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-sdk-protos</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- statefun-flink spi -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-flink-io</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-flink-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- Pre bundled ingress/egress -->
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-kafka-io</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.kzmlabs.flinkstatefun</groupId>
            <artifactId>statefun-kinesis-io</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-aws-kinesis-streams</artifactId>
        </dependency>
        <!-- flink  -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <!-- flink kafka connector -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-kafka</artifactId>
            <version>${flink-kafka.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-base</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <!-- 3rd party -->
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </dependency>

        <!-- test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
        </dependency>
    </dependencies>

</project>