// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package org.apache.flink.statefun.flink.core;
option java_package = "org.apache.flink.statefun.flink.core.generated";
option java_multiple_files = true;

message EnvelopeAddress {
    string namespace = 1;
    string type = 2;
    string id = 3;
}

message Payload {
    string class_name = 2;
    bytes payload_bytes = 3;
}

message Checkpoint {
    int64 checkpoint_id = 1;
}


message Envelope {
    EnvelopeAddress source = 1;
    EnvelopeAddress target = 2;

    // an optional token that can be used track delayed message cancellation.
    string cancellation_token = 10;

    oneof body {
        Checkpoint checkpoint = 4;
        Payload payload = 3;
    }
}
