# SPDX-License-Identifier: Apache-2.0
# Copyright 2014 The Apache Software Foundation


ARG IMAGE_REGISTRY_PREFIX=
ARG BASE_IMAGE=${IMAGE_REGISTRY_PREFIX}golang:1.16-alpine
FROM ${BASE_IMAGE}
RUN apk add --no-cache git

RUN mkdir -p /app/test/smoketest
WORKDIR /app

ADD source/ /app/
ADD smoketest/ /app/v3/test/smoketest/
RUN ls && cd v3/test/smoketest && go build

ADD ssl/server.crt v3/test/smoketest/server.crt
ADD ssl/server.key v3/test/smoketest/server.key

EXPOSE 443
CMD ./v3/test/smoketest/smoketest
