# SPDX-License-Identifier: Apache-2.0
# Copyright 2014 The Apache Software Foundation

baseURL = '//github.com/kzmlabs/flink-statefun'
languageCode = "en-us"
title = "Kzmlabs Flink Stateful Functions"
enableGitInfo = false
theme = "book"
pygmentsUseClasses = true

[params]
  # Flag whether this is a stable version or not.
  # Used for the quickstart page.
  IsStable = false

  # Flag to indicate whether an outdated warning should be shown.
  ShowOutDatedWarning = false

  # This are the version referenced in the docs. Please only use these variables
  # to reference a specific Flink version, because this is the only place where
  # we change the version for the complete docs when forking of a release branch
  # etc.
  # The full version string as referenced in Maven (e.g. 1.2.1)
  Version = "3.4.0-KZM-3.0"

  # For stable releases, leave the bugfix version out (e.g. 1.2). For snapshot
  # release this should be the same as the regular version
  VersionTitle = "3.4.0-KZM-3.0"

  # The branch for this version of Kzmlabs Flink Stateful Functions
  Branch = "release"

  # The github repository for Kzmlabs Flink Stateful Functions
  Repo = "//github.com/kzmlabs/flink-statefun"

  GithubRepo = "https://github.com/kzmlabs/flink-statefun.git"

  # This suffix is appended to the Scala-dependent Maven artifact names
  ScalaVersion = "_2.12"

  ProjectHomepage = "//github.com/kzmlabs/flink-statefun"

  # External links at the bottom
  # of the menu
  MenuLinks = [
    ["GitHub", "//github.com/kzmlabs/flink-statefun"],
  ]

  PreviousDocs = [
  ]

[markup]
[markup.goldmark.renderer]
  unsafe = true
