name: Doc Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - name: Build and Check Documentation
        run: ./tools/ci/docs.sh